### ISSUE TITLE
Could not open input file: /config/www/nextcloud/cron.php

### ISSUE THREAD

**Issue by beodoble** [haberda/nextcloud-addon#100]
Hi all,

I've been using this addon for one month or so and I'm really happy with it. Recently the addon starts but the log in HA shows the following error:

Could not open input file: /config/www/nextcloud/cron.php

Nextcloud is unreachable from the internet (I use nginx proxy manager). From LAN, it works.

Any clue if the error in the log from nextcloud addon may be related with the accessibility issue? in nginx one nothing has changed recently and the rest of proxy host are working correctly.

Any help is grateful.

**Comment by haberda** [comment]
I don't think the issues would be related. If it is accessible via the local network the reverse proxy should work, but I am not sure. I use the cloudflare tunnels add-on, not reverse proxy.

As far as the file, there must be some reference in one if your files somewhere to the /config path. That is where the upstream container places files for persistent storage. The add-on has to use the /data path so when the container builds it modifies the startup files.

I don't see this error, so it would be a guessing game as to which file it is. If you are familiar with the command line  you can exec into the container using the ssh addon and grep all the files in the /data/config or /share/nextcloud directories for that string, then change it.

I'd start by checking /data/config/crontabs/root

Once you find the file just correct the path and the error should stop.

**Comment by beodoble** [comment]
Thanks for the prompt answer. I also agree they are most probably different problems.
Regarding the cron.php file. I have accessed via command line. The file is in /data/config/www/nextcloud/ directory. Crontab looks for /config/www/nextcloud/cron.php. I have just added /data at the beginning. It seems solved.

I'll continue with the access issue from outside.

Thanks again! :)

**Comment by haberda** [comment]
No problem.

Just to be sure, did you add your external URL to the config.php file?

I assume yes, but if you have not checked since the problem has arisen, can you check that file?

**Comment by beodoble** [comment]
Are you referring to the trusted_domains key? if this is the case, yes, I checked it, I have both, my external domain name as well as the internal IP (to be able to access it through LAN for testing purposes).
