### ISSUE TITLE
Cannot create or write into the data directory /share/nextcloud

### ISSUE THREAD

**Issue by hindseb** [haberda/nextcloud-addon#101]
Hi,
I am trying to install NextCloud. As recommended, I would like to set the Data folder to /share/nextcloud. However, I get the following error: Cannot create or write into the data directory /share/nextcloud

Any idea why and how to solve it?

**Comment by haberda** [comment]
Does the DIR already exist? The add-on needs to be the owner of the directory, if it already exists then it probably doesn't have the permissions to take ownership.

If you are not on HASSOS then it's possible the entire /share dir has the wrong permissions.
