### ISSUE TITLE
Read permissions for other addons

### ISSUE THREAD

**Issue by panhans** [haberda/nextcloud-addon#76]
Hi there,

I want to backup my nextcloud files with the [duplicati addon](https://github.com/adrianoamalfi/hassos-addons/).
The problem is, the addon has no access to read the nextcloud directory.

Is there a way to get permissions to the directory? Maybe you can add an option that other addons can get read access to it?

Thanks in advance!

**Comment by haberda** [comment]
The folder has to be owned by the Nextcloud user. However, you should be able to set permissions to whatever you want with the terminal

**Comment by panhans** [comment]
Yes, but after restarting the nextcloud addon and even during runtime the permission change is gone. :\

![image](https://user-images.githubusercontent.com/4427249/201621701-18530a45-c605-416a-97ed-a8b320922325.png)

**Comment by haberda** [comment]
I try and not change much from the upstream container aside from what is required to make it work to reduce maintenance overhead. I'll try and make a change to the script I inject but it may not work/have unintended consequences.
